Ccfg.ypp:	assign_stmt2last brac2S code2args S12init block_stmt2expr  ccfg_header main_function
	cp ccfg_header Ccfg.ypp
	cat code2args >> Ccfg.ypp
	cat brack2S >> Ccfg.ypp
	cat S12init >> Ccfg.ypp
	cat block_stmt2expr >> Ccfg.ypp
	cat assign_stmt2last >> Ccfg.ypp
	cat main_function >> Ccfg.ypp
